### ISSUE TITLE
Microsoft Sculpt Comfort

### ISSUE THREAD

**Issue by chinamcafee** [ultimate-deej/Sculpt-Comfort-Mission-Control#10]
When I clicked the blue button of Microsoft Sculpt Comfort, it doesn't work, but the swipe gesture works fine. How can I make click event work? My system version is 10.12.5, and I use the default plist.

Best wishes.

**Comment by ultimate-deej** [comment]
Hi, @chinamcafee!
What's the output of `defaults read com.apple.dock scmc`?

**Comment by chinamcafee** [comment]
Thank you for your reply, the output shows as follows:

{
    "click-action" = "mission-control";
    "click-code" = 2;
    "long-click-action" = "application-windows";
    method = "event-tap";
    "swipe-down-action" = "next-space";
    "swipe-down-code" = 4;
    "swipe-up-action" = "previous-space";
    "swipe-up-code" = 3;
}

**Comment by ultimate-deej** [comment]
That is surprising. I didn't expect this config to work with Sculpt Comfort mouse at all.

The `sculpt comfort 1` config should probably work for you.
However, if you use it, the OS might run its own default actions when using the blue button. Currently there is no solution to this.

**Comment by chinamcafee** [comment]
sculpt comfort 1 does work, Thanks a lot

**Comment by isunweihan** [comment]
I have the same problem and the sculpt comfort 1 not work for me at all...
My system version is 10.12.6.

**Comment by chinamcafee** [comment]
@SunWeihan My system version is 10.12.6 too, it does work well, there must be something wrong with your operation.

**Comment by ultimate-deej** [comment]
@SunWeihan Did the default work for you? If not, make sure SIP is disabled.
