### ISSUE TITLE
How to use MS sculpt 1 or 2 config?

### ISSUE THREAD

**Issue by francoisxwb** [ultimate-deej/Sculpt-Comfort-Mission-Control#11]
I'm using a MS sculpt comfort mouse on my 2012 MBA with MacOS Sierra 10.12.4 with default config. The app works fine, single tap on the wheel is mapped to mission control. But when I'm scrolling the wheel fast, it occasionally triggers the mission control action. I'm wondering if I can assign the mission control action to windows button? Currently the win button doesn't work at all.

I read the closed issue and found the same problem. MS sculpt 1 or 2 config seem to solve the problem. But I'm a rookie and new to GitHub, so plz be specific, thx a lot.

Best wishes

**Comment by ultimate-deej** [comment]
1. Choose a config and put it on your desktop
2. Open Terminal.app
3. Type `cd ~/Desktop` and press enter
4. Type `defaults import com.apple.dock sculpt\ comfort\ 1.plist` and press enter. Note: config name may differ
5. Type `killall Dock` and press enter
6. Launch the Sculpt Comfort Mission Control app

**Comment by francoisxwb** [comment]
Thanks you for your patience. I imported sculpt comfort 1.plist, the win button works fine but the swipe actions don't work. I changed the swipe-up-code to 4 and the swipe-down-code to 5. Now my MS sculpt comfort works fine.

Best wishes


![2017-09-09_15-58-10](https://user-images.githubusercontent.com/31581491/30238338-e4a98dd4-9577-11e7-812d-8280a0ea7adc.jpg)
