### ISSUE TITLE
High Sierra Not Compatible?

### ISSUE THREAD

**Issue by francoisxwb** [ultimate-deej/Sculpt-Comfort-Mission-Control#12]
I upgraded to MACOs 10.13. Seems that the app is not working in High Sierra?

**Comment by ultimate-deej** [comment]
I'll investigate as soon as I upgrade too. Can't give an estimated date, however.

**Comment by francoisxwb** [comment]
I confirmed that I disabled SIP.

**Comment by francoisxwb** [comment]
I confirm that I disabled SIP.

**Comment by ultimate-deej** [comment]
Try the config from #14

**Comment by klaek** [comment]
It wouldn't work on a High Sierra upgraded from Sierra.
but WORKS on a fully new installed Sierra.

**Comment by klaek** [comment]
In my case. It wouldn't work on a High Sierra upgraded from Sierra.
but WORKS on a fully new installed High Sierra.

**Comment by ultimate-deej** [comment]
@klaek It works for you now, right?

**Comment by klaek** [comment]
Sorry for late reply. 
Yes! It works for me now! Only after I reinstalled High Sierra.

**Comment by Stooovie** [comment]
I can't get it to work in HS upgraded from Sierra. I use a Sculpt Ergonomic, Windows button is 231, back button is 4, product id is 0x7a5. It worked in ElCap and Sierra. SIP is disabled. Any help? Thanks!

**Comment by ultimate-deej** [comment]
@Stooovie I don't know the reason yet, both because I'm still using Sierra, and because It works on a fresh installation (as per klaek's report)

**Comment by Stooovie** [comment]
The new version works! With my Sculpt Ergonomic. Thanks!

**Comment by ultimate-deej** [comment]
Awesome!

**Comment by ultimate-deej** [comment]
Ah it was not you who opened the issue 😄.
@francoisxwb Can you try out the new version?

**Comment by francoisxwb** [comment]
@ultimate-deej I reinstall the app 2.0 alpha, it works fine on High Sierra, even better than it does on Sierra. Thank you for reminding me and just keep going!!! It's a really awesome application!!!
