### ISSUE TITLE
adding "Command+[" and "Command+]"

### ISSUE THREAD

**Issue by klaek** [ultimate-deej/Sculpt-Comfort-Mission-Control#13]
Sorry to contact here. 
Can you help to add "Command+[" and "Command+]" for swepting up and down.

**Comment by ultimate-deej** [comment]
No need to apologize. This is the correct place for your request.
Do you want to switch between desktops with a keyboard hotkey? If so, this feature is built into the macOS. You don't need an app for that, just open keyboard settings and set the hotkeys there.

**Comment by ultimate-deej** [comment]
@klaek Did I understand you correctly?

**Comment by klaek** [comment]
@ultimate-deej Thank you so much and sorry for late reply.
I was originally wish to use Back and Forward in a Finder window. And I have solve this by another mouse app called MacGestrue. (https://github.com/MacGesture/MacGesture)

So please close this issue. Thank you so much for your time!
