### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by turquoise-turtle** [ultimate-deej/Sculpt-Comfort-Mission-Control#16]

**Comment by ultimate-deej** [comment]
Hey, @turquoise-turtle!

There's nothing to take a screenshot of, as the app is pretty much headless.
Do you have any more questions?

**Comment by turquoise-turtle** [comment]
Ok. So how does the app switch desktops? I can't download it at the moment
but I'm interested in it

**Comment by ultimate-deej** [comment]
It injects itself into Dock, which has all the necessary APIs.

**Comment by turquoise-turtle** [comment]
Ah I'm so sorry. I finally actually looked up images of the mouse and get
that it uses the touch button to switch desktops. Ha ha. Well, I probably
should've looked that up first. Now I get that there's nothing to
screenshot.
I thought it was just a regular mouse that was super comfortable so you
decided to name the project after it

**Comment by ultimate-deej** [comment]
> I thought it was just a regular mouse that was super comfortable so you decided to name the project after it

Pretty accurate haha. The issue seems to be resolved, so I'm closing it. Feel free to to reopen it or create another one if you have any more questions.
