### ISSUE TITLE
Sculpt Comfort Mission Control doesn't start

### ISSUE THREAD

**Issue by MrBRono** [ultimate-deej/Sculpt-Comfort-Mission-Control#18]
I've followed the instructions on adding the SCMC Loader into /System/Library/ScriptingAdditions/,
as well as adding a plist into ~/Library/Preferences/ followed by killing the Dock, but opening Sculpt Comfort Mission Control does nothing. I've allowed it through the unidentified app prompt.
![screen shot](https://user-images.githubusercontent.com/16891427/40931551-5263e6d6-67e0-11e8-889c-6356cf36286e.png)

**Comment by ultimate-deej** [comment]
The app does not have a user interface. Try to use your mouse to see if the app works.

**Comment by MrBRono** [comment]
I'm not sure why but re-plugging the usb receiver helped. No se. I'll close the issue!
