### ISSUE TITLE
Attempted to use this with Dongle version, didn't work

### ISSUE THREAD

**Issue by manor** [ultimate-deej/Sculpt-Comfort-Mission-Control#2]
Similar to a user who reported a similar outcome on reddit, the hardware is this:

https://www.microsoft.com/hardware/ru-ru/p/sculpt-comfort-desktop/L3V-00017

Running this asked for my password twice...

**Comment by ultimate-deej** [comment]
Did you try using the debug tool?
https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt%20Comfort%20Debug%20Tool.app.zip?dl=0
It logs HID events from mouse. Does it log anything when you click/swipe the blue button?

**Comment by manor** [comment]
Yes, but it requires OS X 10.10 -- I have 10.9.5... BTW, the two password requests made by the non-debug tool (Sculpt Comfort Mission Control) were of this form: 
![password_request](https://cloud.githubusercontent.com/assets/596326/9028475/e55e72c4-3982-11e5-83f3-09c1ee800452.png)

**Comment by Rimbo** [comment]
Yeah, that's because it's using the dev tools to inject itself into Dock.app, because the API it's using isn't otherwise published.

**Comment by ultimate-deej** [comment]
Rimbo is right about the password dialog.

As for OS X version, I didn't test it on any version other than 10.10.
Could you try the debug tool again please? I recompiled it for 10.9.
https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt%20Comfort%20Debug%20Tool.app.zip?dl=0

**Comment by manor** [comment]
I was able to run the debug tool but I am not sure what I am supposed to do other than press/swipe the blue button (nothing happened). Am I then supposed to check some log? Also, am I supposed to run the debug tool before/during/after/instead-of "Sculpt Comfort Mission Control"?

**Comment by ultimate-deej** [comment]
You run the debug tool to see what codes the blue button sends. The fact that nothing happened may indicate that your mouse has different identifiers. To check this open Apple Menu -> About This Mac -> More Info -> System Report.
Here is what it looks like in my system:
![screenshot](https://cloud.githubusercontent.com/assets/4563968/9599381/1f90ffc2-509c-11e5-9f7f-a707e1146321.png)
I have bluetooth version so the information is located in Bluetooth section. The section will be different in your case. Look for Product/Vendor ID.

**Comment by ultimate-deej** [comment]
@manor how is it going?

**Comment by manor** [comment]
I reran the tool, saw nothing and found the transceiver here (in the USB Device Tree):

![transceiver](https://cloud.githubusercontent.com/assets/596326/13472687/03bfd0e8-e084-11e5-88e2-68428616fc7e.png)

Is the tool supposed to work if the input is coming in through the USB as opposed to bluetooth?

**Comment by ultimate-deej** [comment]
It should work, but you need a custom config with proper product id (see [Configuration folder](../tree/master/Configuration) for usage instructions, only works with 1.2.0).

Also if you are on El Capitan you need to disable SIP. `csrutil enable --without debug` could be enough, but I'm still not quite sure about that.

**Comment by nsonn26** [comment]
Pressing the blue button using the debug tool gives a code 227 1, and then 227 0 when released, and swiping gives a mess of numbers, so debug tool works fine, as well as the blue button. However, when trying to open the non-debug app, the application logo shows up in the dock, but goes away almost instantly. First time I opened it, I was asked for admin credentials so that Developer Tools Access could do something, but that has since stopped. New to Github, sorry if this is a basic problem, but any help would be greatly appreciated. Using a 2015 MBP on OSX 10.11.6

**Comment by ultimate-deej** [comment]
@nsonn26 `alternative mouse revision.plist` config should work out well for you. Disappearing logo is ok, this is how the app works. Note that SIP must be disabled either partially (`csrutil enable --without debug`) or completely (`csrutil disable`) in order for the app to work on El Capitan.

**Comment by nsonn26** [comment]
I've got `csrutil disable` done, however I'm not clear on how to import the `alternative mouse revision.plist` Not sure what I did wrong, so I'll just go step by step. I downloaded the master files, unzipped them, then opened Terminal and entered `defaults import com.apple.dock alternate-mouse-revision.plist`. Terminal's reply was "Could not read data from alternative-mouse-revision.plist." I tried variations on the entry, with different punctuation, all to no avail. Many thanks for assistance.

**Comment by ultimate-deej** [comment]
First, make sure you are in the folder where the config is located. Type `pwd` to see current directory. Second, check if you are entering correct file name. The `alternative mouse revision.plist` file in this repo does not contain any hyphens in its name. So the correct command is `defaults import com.apple.dock alternative\ mouse\ revision.plist`. Alternatively, you can rename the file to something more simple, say `x.plist`, so the command becomes `defaults import com.apple.dock x.plist`.

**Comment by nsonn26** [comment]
Got it working, thanks for the help!
