### ISSUE TITLE
Possible to work with MS Sculpt Ergonomic Mouse

### ISSUE THREAD

**Issue by Stooovie** [ultimate-deej/Sculpt-Comfort-Mission-Control#4]
Right now it doesn't seem to work with MS Sculpt Ergonomic Mouse, only with Sculpt Comfort. Even the logging app doesn't show anything when running. Would it be possible to extend the app to Ergo Mouse as well?

**Comment by ultimate-deej** [comment]
Open Apple Menu -> About This Mac -> [More Info] -> System Report.
Find information related to your mouse and send me Product/Vendor ID.
![screenshot](https://cloud.githubusercontent.com/assets/4563968/9600019/127af9d2-50a1-11e5-8056-9fac1df47d77.png)

**Comment by Stooovie** [comment]
Product ID: 0x07a5
Vendor ID: 0x045e  (Microsoft Corporation)

It's the ID of the USB Transceiver 9.0 included with the mouse. I couldn't find any info for the mouse itself.

Thanks!

**Comment by ultimate-deej** [comment]
Check the updated debug tool
https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt%20Comfort%20Debug%20Tool.app.zip?dl=0

**Comment by Stooovie** [comment]
OK so the blue button sends code 231.

**Comment by ultimate-deej** [comment]
Sorry for the long silence. I'm planning to make the app more configurable. That basically means you will be able to specify any arbitrary device identifiers, button codes, and maybe even manually assign certain actions to buttons (e.g. to get 'natural' swipe direction).
I'll start working on the update approximately in 1-2 weeks.

**Comment by Stooovie** [comment]
That's very cool! I'd be happy to pay a little money for that.

**Comment by ultimate-deej** [comment]
Sorry for the delay again. I've released a new version, now you can configure device id and button codes.

**Comment by Stooovie** [comment]
Awesome! Where can I download the binary? I'm not very apt with Xcode. The
built product (.app) runs and then disappears form dock.

2015-11-11 22:27 GMT+01:00 Maxim Naumov <notifications@github.com>:

**Comment by Stooovie** [comment]
It works great! Click blue button for Expose and long-click for App Expose works great! You've jsut made this mouse much more usable for Mac users :)
