### ISSUE TITLE
Not working in El Capitain GM

### ISSUE THREAD

**Issue by ftirej** [ultimate-deej/Sculpt-Comfort-Mission-Control#5]
When i swipe or press the button nothing happen.

This is the log when i swipe up and down:

-1 43
43 1
-1 43
227 1
224 1
-1 0
43 0
-1 0
227 0
224 0

-1 42
42 1
-1 42
227 1
224 1
-1 0
42 0
-1 0
227 0
224 0

And this is the log when i press the button

227 1
227 0

**Comment by gblmarquez** [comment]
Same here, what we can do?

**Comment by ultimate-deej** [comment]
Sorry for my late reply.
A possible reason can be updated Dock binary. At the moment I'm not able to test it on El Capitan.

**Comment by mtunad** [comment]
Any update?

**Comment by ultimate-deej** [comment]
Unfortunately no, I haven't updated yet.

**Comment by clickonchris** [comment]
:+1:

**Comment by clickonchris** [comment]
I'm not a OS X app developer but I cloned your code and tried to run it on my El Capitan machine.

console keeps outputting the following message:

```
(lldb) attach Dock
error: attach failed: cannot attach to process due to System Integrity Protection
```

**Comment by ultimate-deej** [comment]
Can you try to run the app with SIP disabled?

**Comment by clickonchris** [comment]
I disabled SIP by following the instructions at http://apple.stackexchange.com/a/208481

After SIP was disabled I was able to start the app just fine.  button click works as expected.  I never used swipe up/down before today so I can't say if it works the same or not.

Obviously disabling SIP is not a great solution.  There's got to be a way to get this app to play nice with SIP, right?

**Comment by ultimate-deej** [comment]
A partial solution could be to disable only the debug part of SIP: `csrutil enable --without debug`

**Comment by ultimate-deej** [comment]
Ok the issue is kinda resolved so I'm closing it.
