### ISSUE TITLE
Not working on 10.11.3

### ISSUE THREAD

**Issue by denbue** [ultimate-deej/Sculpt-Comfort-Mission-Control#6]
Hey, unfortunatly I can't install the latest release 1.2.0. I doubleclick the file, it asks for my password and closes. Do I need to install any other software to use this?

I use the Sculpt Comfort Mouse (Bluetooth).

edit: I disabled SIP (as discribed in issue #5) which helped the Windows button to work, but the swipes are still not working. Same with version 1.1.2

**Comment by ultimate-deej** [comment]
Have you tried the debug tool? [https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt Comfort Debug Tool.app.zip?dl=1](https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt Comfort Debug Tool.app.zip?dl=1)
What is the output when you swipe?

**Comment by denbue** [comment]
I guess it is working fine. I installed everything from scratch, setup the MicrosoftHelper of IntelliPoint as autostart and - for now - I am using Better Touch Tool to access the gestures. the windows button is not recognized by BTT.

`csrutil enable --without debug` is executed. Your programe is not asking for my password anymore (just noticed).

My log:

Single click:
227 1
227 0

Long click:
227 1
227 0

Swipe down:
4 1
4 0

Swipe up:
5 1
5 0

**Comment by ultimate-deej** [comment]
The app is not tested with other tools, I personally use SCMC alone. Also you need a custom config (see [Configuration folder](../tree/master/Configuration) for usage instructions). According to your log:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scmc</key>
    <dict>
        <key>product-id</key>
        <integer>0x7a2</integer>
        <key>vendor-id</key>
        <integer>0x45e</integer>

        <key>click-code</key>
        <integer>227</integer>
        <key>swipe-up-code</key>
        <integer>5</integer>
        <key>swipe-down-code</key>
        <integer>4</integer>

        <key>click-action</key>
        <string>mission-control</string>
        <key>long-click-action</key>
        <string>application-windows</string>
        <key>swipe-up-action</key>
        <string>previous-space</string>
        <key>swipe-down-action</key>
        <string>next-space</string>
    </dict>
</dict>
</plist>
```

**Comment by ultimate-deej** [comment]
@denbue So, is it working for you?

**Comment by denbue** [comment]
hey, sorry for answering so late. I uninstalled the IntelliPoint driver, disabled SIP, downloaded 1.2 and imported the config. No password was needed on startup. The slide feature works fine but I still cannot get Mission Control to work on Button Press.

BTW: I just noticed that the sliding function is only working because of BetterTouchTool. Super strange.

**Comment by ultimate-deej** [comment]
In the first message you said it worked the other way round. Is it correct? What setup did you have previously (version, custom config/default, other software)?

**Comment by ultimate-deej** [comment]
Super strange indeed. What makes it more strange is that the debug tool appears to work.

**Comment by denbue** [comment]
That's what I mean. Maybe there are still some file leftovers or whatsoever. I will try to clean everything and then do it from scratch again. More important, I am wondering why I dont get the password request. After start, will the program be a process in the background? Or is there something else than the debug tool that I can monitor?

**Comment by ultimate-deej** [comment]
The password request was necessary to install developer tools and it only has to be done once. After start the app loads itself into Dock process (to access its internal functionality like switching spaces). It doesn't exist as a separate process.

The debug tool is not coupled to the main app in any way. It just uses the same API to receive HID events from mouse, and outputs it as text.

There are some monitor tools on the internet, but none of them actually worked for my mouse.

**Comment by denbue** [comment]
Is there are a way to remove the developer tools? I remember when I tried the app for the first times that I had to enter the password everytime I started it.

**Comment by ultimate-deej** [comment]
I was inaccurate: the tools are called Command Line Tools. Also the password request could be due to starting lldb (part of the tools).

As to how to remove them, do you have Xcode installed? If not, try to remove /Library/Developer/CommandLineTools folder.

**Comment by denbue** [comment]
Thanks, I will give it a try this evening and update this comment with the results.

**Comment by denbue** [comment]
Hey, sorry for not coming back. I could not get it to work, so I gave up. I tried out 1.3 and its working perfect, thanks. Every button. Did not change anything on the config, just executed the file.
One thing that I noticed: The swipe and scroll click are upside down, that means when I swipe down it executes a swipe up. When I click left direction with the scroll wheel it executes a scroll right. Is it just me?

**Comment by ultimate-deej** [comment]
Thank you for your response.
Well, if you don't use event tap method, 1.3 is no different from 1.2.
Regarding the actions reversed, can you try applying the default config and see if anything changes?

**Comment by denbue** [comment]
hey, I imported the default config aaand it stopped working again :) Imported also the config above, but no change.
But hey, I enjoyed the 24hrs working :)

edit: I did a restart and now everything is working fine. So, after three months this issue can be closed ;)
