### ISSUE TITLE
Sierra Compatibility

### ISSUE THREAD

**Issue by ThisIsAlanB** [ultimate-deej/Sculpt-Comfort-Mission-Control#8]
Edit: I was able to get it compiled but it's not working in the latest Sierra GM.

**Comment by ultimate-deej** [comment]
I suppose SIP is still there in Sierra. So you may need to turn it off.
Second, make sure you use the correct config.
Debug tool may help https://www.dropbox.com/s/r1ibabs11x7o3y7/Sculpt%20Comfort%20Debug%20Tool.app.zip?dl=0
It displays button codes

**Comment by ThisIsAlanB** [comment]
Disabled SIP and ran the app again. Still nothing.

Would the default config be the right one?

Debug

```
227 1
227 0
5 1
5 0
4 1
4 0
```

*edit I imported default.plist through terminal (even with the sudo command and killall Dock) and still nothing. Again let me know if there's something I'm missing.

**Comment by ultimate-deej** [comment]
use the config from here: https://github.com/ultimate-deej/Sculpt-Comfort-Mission-Control/issues/6#issuecomment-185746879

**Comment by ThisIsAlanB** [comment]
Still nothing. Don't know if this is related with my issue, but every time I open the app, it pops this up twice. I type my password both times and the app stalls in the dock a bit before closing.
<img width="555" alt="screen shot 2016-09-18 at 11 49 25 pm" src="https://cloud.githubusercontent.com/assets/13711807/18622325/90886282-7dfb-11e6-8c4d-e19d5a9f05f7.png">

**Comment by ultimate-deej** [comment]
The way app icon behaves means that injecting most likely goes without problems.
As to why is asks your password every time, I don't now.

I personally still use El Capitan. It is possible that Apple has changed `Dock` internals, which the app relies on. In that case the app won't work until I install Sierra and see what has changed and modify the app accordingly.

So, if injecting is actually ok, and your config is correct, the app should work.

As the last resort, try running the app via Terminal and copy the output here. Or, if it fails for some reason, run it from Xcode and copy the app output from there.

**Comment by ThisIsAlanB** [comment]
This is what I get when trying to run the app through Xcode:

```
(lldb) attach Dock
Process 1541 stopped
* thread #1: tid = 0x2122b, 0x00007fffea6c141a libsystem_kernel.dylib`mach_msg_trap + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fffea6c141a libsystem_kernel.dylib`mach_msg_trap + 10
libsystem_kernel.dylib`mach_msg_trap:
->  0x7fffea6c141a <+10>: retq   
    0x7fffea6c141b <+11>: nop    

libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x7fffea6c141c <+0>:  movq   %rcx, %r10
    0x7fffea6c141f <+3>:  movl   $0x1000020, %eax          ; imm = 0x1000020 

Executable module set to "/System/Library/CoreServices/Dock.app/Contents/MacOS/Dock".
Architecture set to: x86_64h-apple-macosx.
(lldb) expr (char)[[NSBundle bundleWithPath:@"/Users/Alan/Library/Developer/Xcode/DerivedData/Sculpt_Comfort_Mission_Control-eikthdmlpxciqvfzfntvsbiliujo/Build/Products/Debug/Sculpt Comfort Mission Control.app/Contents/Resources/Sculpt Control Inject Bundle.bundle"] load]
(char) $0 = '\x01'
(lldb) detach
Process 1541 detached
(lldb) (lldb) quit
```

**Comment by ultimate-deej** [comment]
I can see that bundle is successfully injected here.
It is possible that Sierra has introduced incompatible changes to Dock binary. Check if Dock restarts after launching the app or after clicking win-button. The restart may happen due to a crash caused by binary incompatibility. There are two ways to do this:
- Desktop background turns black for a moment (faster way)
- Open `Activity Monitor` and see if PID of `Dock` process has changed (more reliable)

**Comment by ThisIsAlanB** [comment]
PID doesn't change at all in Activity Mon

**Comment by ultimate-deej** [comment]
Ok, there is one more thing we can try. Open terminal and type `defaults read com.apple.dock scmc`. The output should be your config. If it is not, try to import it once again.
My output:
![screen shot 2016-09-20 at 16 35 29](https://cloud.githubusercontent.com/assets/4563968/18672310/bc7faa22-7f58-11e6-98b4-51023f0d6295.png)

**Comment by ThisIsAlanB** [comment]
Mine's the same minus swipe-down-code being 4 and swipe-up-code being 5. Click actions are the same, but clicking the Windows button doesn't do anything.

**Comment by ultimate-deej** [comment]
Everything looks ok except the OS version. It seems that nothing can be done here until I install Sierra and see why it doesn't work. Unfortunately, I don't plan to upgrade in the near future.

**Comment by ThisIsAlanB** [comment]
Alright. Thanks for all of the the help anyway!

**Comment by ultimate-deej** [comment]
You are welcome! I will let you know if I manage to work it out.

**Comment by AhmedKamal** [comment]
@ultimate-deej First Thanks a lot for your efforts. Is there any updates regarding this ?

**Comment by ultimate-deej** [comment]
@AhmedKamal not yet, I still haven't upgraded to Sierra. I was thinking of making a plugin for SIMBL, it appears to be working on Sierra.

**Comment by ultimate-deej** [comment]
@ThisIsAlanB @AhmedKamal Check out [the latest release](../releases/tag/1.4.0)

**Comment by ultimate-deej** [comment]
So, according to #10 and my own test on a few Macs, it works now.
