### ISSUE TITLE
Sculpt Ergonomic Mouse

### ISSUE THREAD

**Issue by calebeaires** [ultimate-deej/Sculpt-Comfort-Mission-Control#9]
I opened this issue to ask for help about **Sculpt Ergonomic Mouse** on MacOS. The pointer keep "jumping" while I'm moving the mouse.

I have tried everting Mac foruns says to do, but I am aware that it is the missing Microsoft driver. I found this good github project to Sculpt Confort, so I an asking if do you have some workaround to this another Sculpt Ergonomic mouse as they seems to be similar ones?

**Comment by ultimate-deej** [comment]
Sorry, I don't have any.
This app can't help you too since it doesn't interfere in mouse movement.

Though, I had a similar issue when I installed SmoothMouse app. Do you have any mouse drivers or helper apps installer? They might be the cause.
